#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

if [ -f ~/.config/exercism/exercism_completion.zsh ]; then
  . ~/.config/exercism/exercism_completion.zsh
fi

alias vi="/usr/local/bin/vim"
alias vim="/usr/local/bin/vim"
alias vimdiff="/usr/local/bin/vimdiff"

export EDITOR='vim'
export VISUAL='vim'
export GOPATH=~/.go
export PATH=/usr/lib/go-latest/bin:$HOME/bin:$PATH:$GOPATH/bin:HOME/.yarn/bin:$HOME/Code/flutter/bin:$PATH
